# Copyright (c) 2022 RIKEN
# All rights reserved.
#
# This software is released under the MIT License.
# http://opensource.org/licenses/mit-license.php

CARGO = cargo

clean:
	$(CARGO) clean

fmt:
	$(CARGO) fmt 
