# Copyright (c) 2022 RIKEN
# Copyright (c) 2022 National Institute of Advanced Industrial Science and Technology (AIST)
# All rights reserved.
#
# This software is released under the MIT License.
# http://opensource.org/licenses/mit-license.php

[package]
name = "hypervisor_kernel"
version = "1.0.0"
edition = "2021"

[features]
default = ["smmu", "i210", "mt27800", "fast_restore", "acpi_table_protection", "contiguous_bit", "advanced_memory_manager"]
smmu = []
i210 = []
mt27800 = []
fast_restore = []
acpi_table_protection = []
contiguous_bit = []
a64fx = []
advanced_memory_manager = ["common/advanced_memory_manager"]
tftp = []

[dependencies]
common = { path = "../common" }

[profile.release]
strip = "symbols"
