name: Build Hypervisor (Stable)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build_stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cd src && cargo xtask build -r -p
      - uses: actions/upload-artifact@v4
        with:
          name: MilvusVisor
          path: src/bin/
          compression-level: 9
