name: Rustfmt

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run cargo fmt
        id: fmt
        continue-on-error: true
        run: |
          cd src
          echo -e "\`cargo fmt --check\` is failed.\n\`\`\`diff" > /tmp/message
          cargo fmt --all --check -- --color never >> /tmp/message
      - name: Report format error
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REF: ${{ github.event.pull_request.html_url }}
        run: |
          echo "\`\`\`" >> /tmp/message
          gh pr comment -F /tmp/message "$REF"
        if: steps.fmt.outcome != 'success'

