name: Rust

on:
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
  schedule:
    - cron: '15 4 */1 * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install tools
      run: |
        rustup default nightly
        rustup component add rust-src
        mkdir bin

    - name: Build UEFI bootloader
      run: |
        cd src
        make bootloader
        mv   target/*/release/hypervisor_bootloader.efi ../bin/BOOTAA64.EFI

    - name: Build kernel
      run: |
        cd src
        make kernel
        mv   target/*/release/hypervisor_kernel ../bin/hypervisor_kernel

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: MilvusVisor
        path: bin/

    
